# Generated by Django 3.0.2 on 2020-10-18 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20201018_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dedline',
            field=models.DateField(default=datetime.date.today, verbose_name='Deadline of the project (year, month, day)'),
        ),
    ]
