# Generated by Django 3.0.2 on 2020-10-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_project_dedline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dedline',
        ),
    ]
