# Generated by Django 3.0.2 on 2020-10-19 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_project_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.date.today, verbose_name='Deadline of the task (year, month, day)'),
        ),
    ]
