# Generated by Django 3.0.2 on 2020-10-20 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('order', models.IntegerField(default=100000)),
            ],
        ),
    ]
