# Generated by Django 3.0.2 on 2020-10-23 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='task',
            name='lookup_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=100000),
        ),
    ]
