# Generated by Django 3.0.2 on 2020-10-23 17:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20201023_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('order', models.IntegerField(default=100000)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='lookup_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
    ]
